### ISSUE TITLE
about mybatis.mapper-locations

### ISSUE THREAD

**Issue by vovo28** [quarkiverse/quarkus-mybatis#219]
Could you provide details for  ["quarkus.mybatis.mapper-locations"] property?

I  set application-dev.yaml

```
quarkus:
     mybatis:
         mapper-locations:
             - "classpath*:mapper/*Mapper.xml"
```

But error occurs: 
org.apache.ibatis.binding.BindingException: Invalid bound statement (not found): org.intco.EmailRecordMapper.getObjects
