### ISSUE TITLE
Support multiple files in quarkus.mybatis.initial-sql

### ISSUE THREAD

**Issue by p91paul** [quarkiverse/quarkus-mybatis#341]
It can be useful to be able to specify multiple initial sql files, expecially if one or more of them is generated.
Currently initial-sql seems to support a single file (https://github.com/quarkiverse/quarkus-mybatis/blob/a3b6fa47df80d1dc684633dc1c97175e4f5d2a5c/mybatis/runtime/src/main/java/io/quarkiverse/mybatis/runtime/MyBatisRecorder.java#L428), can it be enhanced to be able to specify many files?

To cite similar implementations in other frameworks, Spring supports this behavior through the spring.sql.init.schema-locations configuration; multiple files can be specified with a comma separator, like this:

```
spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: sa
  sql:
    init:
      schema-locations: classpath*:test-data/schema-h2.sql,classpath*:test-data/tables-h2.sql,classpath*:test-data/alias-h2.sql
```
